id: P005390
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 2021-12-17 11:47:51.883495
source_metadata:
  id: bdr:W1KG14516
  title: ཕ་ཡུལ། ཕ་ཡུལ།
  author: ''
  volumes:
    dd7411601b724510bf344efc04d516e0:
      image_group_id: I1KG15666
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
