id: P005390
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG14516
  title: ཕ་ཡུལ། ཕ་ཡུལ།
  author: ''
  volumes:
    dd7411601b724510bf344efc04d516e0:
      image_group_id: I1KG15666
      title: ''
      volume_number: 1
      total_pages: 282
      base_file: v001.txt
